### ISSUE TITLE
How to update the website

### ISSUE THREAD

**Issue by Cliftonz** [ius-csg/ccdc-handbook#2]
I have put a new documention into the files but it has not updated. How do I fix that?
How do I add a file to use?

**Comment by TheOtherUnknown** [comment]
We don't have write access yet, it seems. @jasekiw needs to give us the rest of the access.

**Comment by jasekiw** [comment]
@Cliftonz I have given everyone access to push now, You should not be able to make edits.

**Comment by jasekiw** [comment]
@Cliftonz  I can see your changes on https://ccdc-handbook.firebaseapp.com/. I will consider this issue closed
