### ISSUE TITLE
Setion bar at the top

### ISSUE THREAD

**Issue by Cliftonz** [ius-csg/ccdc-handbook#3]
With the addition of the New Portal/pages, The the bar on the top is covering up the top part of the writing in the pages.

**Comment by TheOtherUnknown** [comment]
I can correct this by changing the theme of the site. We can either use:
* [Readthedocs](https://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs)
* Or a [third-party theme](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)

Personally, I like Material. 
Thoughts?

**Comment by TheOtherUnknown** [comment]
Fixed with 7377240
